# Chrome Browser Engine - Prometheus Configuration
# Production monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'chrome-browser-engine'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Browser Engine metrics
  - job_name: 'browser-engine'
    static_configs:
      - targets: ['browser-engine:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scheme: 'http'

  # Browser Demo metrics
  - job_name: 'browser-demo'
    static_configs:
      - targets: ['browser-demo:9090']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'http'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s
    metrics_path: '/nginx_status'
    scheme: 'http'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
